import * as stylex from '@stylexjs/stylex';
import { primaryColors } from '../colors/primary.stylex';
import { radixColors } from '../radix.stylex';

export const accentPrimary = stylex.createTheme(radixColors, {
    accent1: `light-dark(${primaryColors.light1}, ${primaryColors.dark1})`,
    accentLight1: primaryColors.light1,
    accentDark1: primaryColors.dark1,
    accentA1: `light-dark(${primaryColors.lightA1}, ${primaryColors.darkA1})`,
    accentLightA1: primaryColors.lightA1,
    accentDarkA1: primaryColors.darkA1,
    accent2: `light-dark(${primaryColors.light2}, ${primaryColors.dark2})`,
    accentLight2: primaryColors.light2,
    accentDark2: primaryColors.dark2,
    accentA2: `light-dark(${primaryColors.lightA2}, ${primaryColors.darkA2})`,
    accentLightA2: primaryColors.lightA2,
    accentDarkA2: primaryColors.darkA2,
    accent3: `light-dark(${primaryColors.light3}, ${primaryColors.dark3})`,
    accentLight3: primaryColors.light3,
    accentDark3: primaryColors.dark3,
    accentA3: `light-dark(${primaryColors.lightA3}, ${primaryColors.darkA3})`,
    accentLightA3: primaryColors.lightA3,
    accentDarkA3: primaryColors.darkA3,
    accent4: `light-dark(${primaryColors.light4}, ${primaryColors.dark4})`,
    accentLight4: primaryColors.light4,
    accentDark4: primaryColors.dark4,
    accentA4: `light-dark(${primaryColors.lightA4}, ${primaryColors.darkA4})`,
    accentLightA4: primaryColors.lightA4,
    accentDarkA4: primaryColors.darkA4,
    accent5: `light-dark(${primaryColors.light5}, ${primaryColors.dark5})`,
    accentLight5: primaryColors.light5,
    accentDark5: primaryColors.dark5,
    accentA5: `light-dark(${primaryColors.lightA5}, ${primaryColors.darkA5})`,
    accentLightA5: primaryColors.lightA5,
    accentDarkA5: primaryColors.darkA5,
    accent6: `light-dark(${primaryColors.light6}, ${primaryColors.dark6})`,
    accentLight6: primaryColors.light6,
    accentDark6: primaryColors.dark6,
    accentA6: `light-dark(${primaryColors.lightA6}, ${primaryColors.darkA6})`,
    accentLightA6: primaryColors.lightA6,
    accentDarkA6: primaryColors.darkA6,
    accent7: `light-dark(${primaryColors.light7}, ${primaryColors.dark7})`,
    accentLight7: primaryColors.light7,
    accentDark7: primaryColors.dark7,
    accentA7: `light-dark(${primaryColors.lightA7}, ${primaryColors.darkA7})`,
    accentLightA7: primaryColors.lightA7,
    accentDarkA7: primaryColors.darkA7,
    accent8: `light-dark(${primaryColors.light8}, ${primaryColors.dark8})`,
    accentLight8: primaryColors.light8,
    accentDark8: primaryColors.dark8,
    accentA8: `light-dark(${primaryColors.lightA8}, ${primaryColors.darkA8})`,
    accentLightA8: primaryColors.lightA8,
    accentDarkA8: primaryColors.darkA8,
    accent9: `light-dark(${primaryColors.light9}, ${primaryColors.dark9})`,
    accentLight9: primaryColors.light9,
    accentDark9: primaryColors.dark9,
    accentA9: `light-dark(${primaryColors.lightA9}, ${primaryColors.darkA9})`,
    accentLightA9: primaryColors.lightA9,
    accentDarkA9: primaryColors.darkA9,
    accent10: `light-dark(${primaryColors.light10}, ${primaryColors.dark10})`,
    accentLight10: primaryColors.light10,
    accentDark10: primaryColors.dark10,
    accentA10: `light-dark(${primaryColors.lightA10}, ${primaryColors.darkA10})`,
    accentLightA10: primaryColors.lightA10,
    accentDarkA10: primaryColors.darkA10,
    accent11: `light-dark(${primaryColors.light11}, ${primaryColors.dark11})`,
    accentLight11: primaryColors.light11,
    accentDark11: primaryColors.dark11,
    accentA11: `light-dark(${primaryColors.lightA11}, ${primaryColors.darkA11})`,
    accentLightA11: primaryColors.lightA11,
    accentDarkA11: primaryColors.darkA11,
    accent12: `light-dark(${primaryColors.light12}, ${primaryColors.dark12})`,
    accentLight12: primaryColors.light12,
    accentDark12: primaryColors.dark12,
    accentA12: `light-dark(${primaryColors.lightA12}, ${primaryColors.darkA12})`,
    accentLightA12: primaryColors.lightA12,
    accentDarkA12: primaryColors.darkA12
});
