import * as stylex from '@stylexjs/stylex';
import { secondaryColors } from '../colors/secondary.stylex';
import { radixColors } from '../radix.stylex';

export const accentSecondary = stylex.createTheme(radixColors, {
    accent1: `light-dark(${secondaryColors.light1}, ${secondaryColors.dark1})`,
    accentLight1: secondaryColors.light1,
    accentDark1: secondaryColors.dark1,
    accentA1: `light-dark(${secondaryColors.lightA1}, ${secondaryColors.darkA1})`,
    accentLightA1: secondaryColors.lightA1,
    accentDarkA1: secondaryColors.darkA1,
    accent2: `light-dark(${secondaryColors.light2}, ${secondaryColors.dark2})`,
    accentLight2: secondaryColors.light2,
    accentDark2: secondaryColors.dark2,
    accentA2: `light-dark(${secondaryColors.lightA2}, ${secondaryColors.darkA2})`,
    accentLightA2: secondaryColors.lightA2,
    accentDarkA2: secondaryColors.darkA2,
    accent3: `light-dark(${secondaryColors.light3}, ${secondaryColors.dark3})`,
    accentLight3: secondaryColors.light3,
    accentDark3: secondaryColors.dark3,
    accentA3: `light-dark(${secondaryColors.lightA3}, ${secondaryColors.darkA3})`,
    accentLightA3: secondaryColors.lightA3,
    accentDarkA3: secondaryColors.darkA3,
    accent4: `light-dark(${secondaryColors.light4}, ${secondaryColors.dark4})`,
    accentLight4: secondaryColors.light4,
    accentDark4: secondaryColors.dark4,
    accentA4: `light-dark(${secondaryColors.lightA4}, ${secondaryColors.darkA4})`,
    accentLightA4: secondaryColors.lightA4,
    accentDarkA4: secondaryColors.darkA4,
    accent5: `light-dark(${secondaryColors.light5}, ${secondaryColors.dark5})`,
    accentLight5: secondaryColors.light5,
    accentDark5: secondaryColors.dark5,
    accentA5: `light-dark(${secondaryColors.lightA5}, ${secondaryColors.darkA5})`,
    accentLightA5: secondaryColors.lightA5,
    accentDarkA5: secondaryColors.darkA5,
    accent6: `light-dark(${secondaryColors.light6}, ${secondaryColors.dark6})`,
    accentLight6: secondaryColors.light6,
    accentDark6: secondaryColors.dark6,
    accentA6: `light-dark(${secondaryColors.lightA6}, ${secondaryColors.darkA6})`,
    accentLightA6: secondaryColors.lightA6,
    accentDarkA6: secondaryColors.darkA6,
    accent7: `light-dark(${secondaryColors.light7}, ${secondaryColors.dark7})`,
    accentLight7: secondaryColors.light7,
    accentDark7: secondaryColors.dark7,
    accentA7: `light-dark(${secondaryColors.lightA7}, ${secondaryColors.darkA7})`,
    accentLightA7: secondaryColors.lightA7,
    accentDarkA7: secondaryColors.darkA7,
    accent8: `light-dark(${secondaryColors.light8}, ${secondaryColors.dark8})`,
    accentLight8: secondaryColors.light8,
    accentDark8: secondaryColors.dark8,
    accentA8: `light-dark(${secondaryColors.lightA8}, ${secondaryColors.darkA8})`,
    accentLightA8: secondaryColors.lightA8,
    accentDarkA8: secondaryColors.darkA8,
    accent9: `light-dark(${secondaryColors.light9}, ${secondaryColors.dark9})`,
    accentLight9: secondaryColors.light9,
    accentDark9: secondaryColors.dark9,
    accentA9: `light-dark(${secondaryColors.lightA9}, ${secondaryColors.darkA9})`,
    accentLightA9: secondaryColors.lightA9,
    accentDarkA9: secondaryColors.darkA9,
    accent10: `light-dark(${secondaryColors.light10}, ${secondaryColors.dark10})`,
    accentLight10: secondaryColors.light10,
    accentDark10: secondaryColors.dark10,
    accentA10: `light-dark(${secondaryColors.lightA10}, ${secondaryColors.darkA10})`,
    accentLightA10: secondaryColors.lightA10,
    accentDarkA10: secondaryColors.darkA10,
    accent11: `light-dark(${secondaryColors.light11}, ${secondaryColors.dark11})`,
    accentLight11: secondaryColors.light11,
    accentDark11: secondaryColors.dark11,
    accentA11: `light-dark(${secondaryColors.lightA11}, ${secondaryColors.darkA11})`,
    accentLightA11: secondaryColors.lightA11,
    accentDarkA11: secondaryColors.darkA11,
    accent12: `light-dark(${secondaryColors.light12}, ${secondaryColors.dark12})`,
    accentLight12: secondaryColors.light12,
    accentDark12: secondaryColors.dark12,
    accentA12: `light-dark(${secondaryColors.lightA12}, ${secondaryColors.darkA12})`,
    accentLightA12: secondaryColors.lightA12,
    accentDarkA12: secondaryColors.darkA12
});
