import * as stylex from '@stylexjs/stylex';
import { tertiaryColors } from '../colors/tertiary.stylex';
import { radixColors } from '../radix.stylex';

export const accentTertiary = stylex.createTheme(radixColors, {
    accent1: `light-dark(${tertiaryColors.light1}, ${tertiaryColors.dark1})`,
    accentLight1: tertiaryColors.light1,
    accentDark1: tertiaryColors.dark1,
    accentA1: `light-dark(${tertiaryColors.lightA1}, ${tertiaryColors.darkA1})`,
    accentLightA1: tertiaryColors.lightA1,
    accentDarkA1: tertiaryColors.darkA1,
    accent2: `light-dark(${tertiaryColors.light2}, ${tertiaryColors.dark2})`,
    accentLight2: tertiaryColors.light2,
    accentDark2: tertiaryColors.dark2,
    accentA2: `light-dark(${tertiaryColors.lightA2}, ${tertiaryColors.darkA2})`,
    accentLightA2: tertiaryColors.lightA2,
    accentDarkA2: tertiaryColors.darkA2,
    accent3: `light-dark(${tertiaryColors.light3}, ${tertiaryColors.dark3})`,
    accentLight3: tertiaryColors.light3,
    accentDark3: tertiaryColors.dark3,
    accentA3: `light-dark(${tertiaryColors.lightA3}, ${tertiaryColors.darkA3})`,
    accentLightA3: tertiaryColors.lightA3,
    accentDarkA3: tertiaryColors.darkA3,
    accent4: `light-dark(${tertiaryColors.light4}, ${tertiaryColors.dark4})`,
    accentLight4: tertiaryColors.light4,
    accentDark4: tertiaryColors.dark4,
    accentA4: `light-dark(${tertiaryColors.lightA4}, ${tertiaryColors.darkA4})`,
    accentLightA4: tertiaryColors.lightA4,
    accentDarkA4: tertiaryColors.darkA4,
    accent5: `light-dark(${tertiaryColors.light5}, ${tertiaryColors.dark5})`,
    accentLight5: tertiaryColors.light5,
    accentDark5: tertiaryColors.dark5,
    accentA5: `light-dark(${tertiaryColors.lightA5}, ${tertiaryColors.darkA5})`,
    accentLightA5: tertiaryColors.lightA5,
    accentDarkA5: tertiaryColors.darkA5,
    accent6: `light-dark(${tertiaryColors.light6}, ${tertiaryColors.dark6})`,
    accentLight6: tertiaryColors.light6,
    accentDark6: tertiaryColors.dark6,
    accentA6: `light-dark(${tertiaryColors.lightA6}, ${tertiaryColors.darkA6})`,
    accentLightA6: tertiaryColors.lightA6,
    accentDarkA6: tertiaryColors.darkA6,
    accent7: `light-dark(${tertiaryColors.light7}, ${tertiaryColors.dark7})`,
    accentLight7: tertiaryColors.light7,
    accentDark7: tertiaryColors.dark7,
    accentA7: `light-dark(${tertiaryColors.lightA7}, ${tertiaryColors.darkA7})`,
    accentLightA7: tertiaryColors.lightA7,
    accentDarkA7: tertiaryColors.darkA7,
    accent8: `light-dark(${tertiaryColors.light8}, ${tertiaryColors.dark8})`,
    accentLight8: tertiaryColors.light8,
    accentDark8: tertiaryColors.dark8,
    accentA8: `light-dark(${tertiaryColors.lightA8}, ${tertiaryColors.darkA8})`,
    accentLightA8: tertiaryColors.lightA8,
    accentDarkA8: tertiaryColors.darkA8,
    accent9: `light-dark(${tertiaryColors.light9}, ${tertiaryColors.dark9})`,
    accentLight9: tertiaryColors.light9,
    accentDark9: tertiaryColors.dark9,
    accentA9: `light-dark(${tertiaryColors.lightA9}, ${tertiaryColors.darkA9})`,
    accentLightA9: tertiaryColors.lightA9,
    accentDarkA9: tertiaryColors.darkA9,
    accent10: `light-dark(${tertiaryColors.light10}, ${tertiaryColors.dark10})`,
    accentLight10: tertiaryColors.light10,
    accentDark10: tertiaryColors.dark10,
    accentA10: `light-dark(${tertiaryColors.lightA10}, ${tertiaryColors.darkA10})`,
    accentLightA10: tertiaryColors.lightA10,
    accentDarkA10: tertiaryColors.darkA10,
    accent11: `light-dark(${tertiaryColors.light11}, ${tertiaryColors.dark11})`,
    accentLight11: tertiaryColors.light11,
    accentDark11: tertiaryColors.dark11,
    accentA11: `light-dark(${tertiaryColors.lightA11}, ${tertiaryColors.darkA11})`,
    accentLightA11: tertiaryColors.lightA11,
    accentDarkA11: tertiaryColors.darkA11,
    accent12: `light-dark(${tertiaryColors.light12}, ${tertiaryColors.dark12})`,
    accentLight12: tertiaryColors.light12,
    accentDark12: tertiaryColors.dark12,
    accentA12: `light-dark(${tertiaryColors.lightA12}, ${tertiaryColors.darkA12})`,
    accentLightA12: tertiaryColors.lightA12,
    accentDarkA12: tertiaryColors.darkA12
});
