import * as stylex from '@stylexjs/stylex';
import { warningColors } from '../colors/warning.stylex';
import { radixColors } from '../radix.stylex';

export const accentWarning = stylex.createTheme(radixColors, {
    accent1: `light-dark(${warningColors.light1}, ${warningColors.dark1})`,
    accentLight1: warningColors.light1,
    accentDark1: warningColors.dark1,
    accentA1: `light-dark(${warningColors.lightA1}, ${warningColors.darkA1})`,
    accentLightA1: warningColors.lightA1,
    accentDarkA1: warningColors.darkA1,
    accent2: `light-dark(${warningColors.light2}, ${warningColors.dark2})`,
    accentLight2: warningColors.light2,
    accentDark2: warningColors.dark2,
    accentA2: `light-dark(${warningColors.lightA2}, ${warningColors.darkA2})`,
    accentLightA2: warningColors.lightA2,
    accentDarkA2: warningColors.darkA2,
    accent3: `light-dark(${warningColors.light3}, ${warningColors.dark3})`,
    accentLight3: warningColors.light3,
    accentDark3: warningColors.dark3,
    accentA3: `light-dark(${warningColors.lightA3}, ${warningColors.darkA3})`,
    accentLightA3: warningColors.lightA3,
    accentDarkA3: warningColors.darkA3,
    accent4: `light-dark(${warningColors.light4}, ${warningColors.dark4})`,
    accentLight4: warningColors.light4,
    accentDark4: warningColors.dark4,
    accentA4: `light-dark(${warningColors.lightA4}, ${warningColors.darkA4})`,
    accentLightA4: warningColors.lightA4,
    accentDarkA4: warningColors.darkA4,
    accent5: `light-dark(${warningColors.light5}, ${warningColors.dark5})`,
    accentLight5: warningColors.light5,
    accentDark5: warningColors.dark5,
    accentA5: `light-dark(${warningColors.lightA5}, ${warningColors.darkA5})`,
    accentLightA5: warningColors.lightA5,
    accentDarkA5: warningColors.darkA5,
    accent6: `light-dark(${warningColors.light6}, ${warningColors.dark6})`,
    accentLight6: warningColors.light6,
    accentDark6: warningColors.dark6,
    accentA6: `light-dark(${warningColors.lightA6}, ${warningColors.darkA6})`,
    accentLightA6: warningColors.lightA6,
    accentDarkA6: warningColors.darkA6,
    accent7: `light-dark(${warningColors.light7}, ${warningColors.dark7})`,
    accentLight7: warningColors.light7,
    accentDark7: warningColors.dark7,
    accentA7: `light-dark(${warningColors.lightA7}, ${warningColors.darkA7})`,
    accentLightA7: warningColors.lightA7,
    accentDarkA7: warningColors.darkA7,
    accent8: `light-dark(${warningColors.light8}, ${warningColors.dark8})`,
    accentLight8: warningColors.light8,
    accentDark8: warningColors.dark8,
    accentA8: `light-dark(${warningColors.lightA8}, ${warningColors.darkA8})`,
    accentLightA8: warningColors.lightA8,
    accentDarkA8: warningColors.darkA8,
    accent9: `light-dark(${warningColors.light9}, ${warningColors.dark9})`,
    accentLight9: warningColors.light9,
    accentDark9: warningColors.dark9,
    accentA9: `light-dark(${warningColors.lightA9}, ${warningColors.darkA9})`,
    accentLightA9: warningColors.lightA9,
    accentDarkA9: warningColors.darkA9,
    accent10: `light-dark(${warningColors.light10}, ${warningColors.dark10})`,
    accentLight10: warningColors.light10,
    accentDark10: warningColors.dark10,
    accentA10: `light-dark(${warningColors.lightA10}, ${warningColors.darkA10})`,
    accentLightA10: warningColors.lightA10,
    accentDarkA10: warningColors.darkA10,
    accent11: `light-dark(${warningColors.light11}, ${warningColors.dark11})`,
    accentLight11: warningColors.light11,
    accentDark11: warningColors.dark11,
    accentA11: `light-dark(${warningColors.lightA11}, ${warningColors.darkA11})`,
    accentLightA11: warningColors.lightA11,
    accentDarkA11: warningColors.darkA11,
    accent12: `light-dark(${warningColors.light12}, ${warningColors.dark12})`,
    accentLight12: warningColors.light12,
    accentDark12: warningColors.dark12,
    accentA12: `light-dark(${warningColors.lightA12}, ${warningColors.darkA12})`,
    accentLightA12: warningColors.lightA12,
    accentDarkA12: warningColors.darkA12
});
