import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { defaultAccentColors } from '../../colors/accent/default.stylex';

export const accentDefault = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ defaultAccentColors.light1 }, ${ defaultAccentColors.dark1 })`,
  alpha1: `light-dark(${ defaultAccentColors.lightA1 }, ${ defaultAccentColors.darkA1 })`,
  light1: defaultAccentColors.light1,
  lightA1: defaultAccentColors.lightA1,
  dark1: defaultAccentColors.dark1,
  darkA1: defaultAccentColors.darkA1,
  color2: `light-dark(${ defaultAccentColors.light2 }, ${ defaultAccentColors.dark2 })`,
  alpha2: `light-dark(${ defaultAccentColors.lightA2 }, ${ defaultAccentColors.darkA2 })`,
  light2: defaultAccentColors.light2,
  lightA2: defaultAccentColors.lightA2,
  dark2: defaultAccentColors.dark2,
  darkA2: defaultAccentColors.darkA2,
  color3: `light-dark(${ defaultAccentColors.light3 }, ${ defaultAccentColors.dark3 })`,
  alpha3: `light-dark(${ defaultAccentColors.lightA3 }, ${ defaultAccentColors.darkA3 })`,
  light3: defaultAccentColors.light3,
  lightA3: defaultAccentColors.lightA3,
  dark3: defaultAccentColors.dark3,
  darkA3: defaultAccentColors.darkA3,
  color4: `light-dark(${ defaultAccentColors.light4 }, ${ defaultAccentColors.dark4 })`,
  alpha4: `light-dark(${ defaultAccentColors.lightA4 }, ${ defaultAccentColors.darkA4 })`,
  light4: defaultAccentColors.light4,
  lightA4: defaultAccentColors.lightA4,
  dark4: defaultAccentColors.dark4,
  darkA4: defaultAccentColors.darkA4,
  color5: `light-dark(${ defaultAccentColors.light5 }, ${ defaultAccentColors.dark5 })`,
  alpha5: `light-dark(${ defaultAccentColors.lightA5 }, ${ defaultAccentColors.darkA5 })`,
  light5: defaultAccentColors.light5,
  lightA5: defaultAccentColors.lightA5,
  dark5: defaultAccentColors.dark5,
  darkA5: defaultAccentColors.darkA5,
  color6: `light-dark(${ defaultAccentColors.light6 }, ${ defaultAccentColors.dark6 })`,
  alpha6: `light-dark(${ defaultAccentColors.lightA6 }, ${ defaultAccentColors.darkA6 })`,
  light6: defaultAccentColors.light6,
  lightA6: defaultAccentColors.lightA6,
  dark6: defaultAccentColors.dark6,
  darkA6: defaultAccentColors.darkA6,
  color7: `light-dark(${ defaultAccentColors.light7 }, ${ defaultAccentColors.dark7 })`,
  alpha7: `light-dark(${ defaultAccentColors.lightA7 }, ${ defaultAccentColors.darkA7 })`,
  light7: defaultAccentColors.light7,
  lightA7: defaultAccentColors.lightA7,
  dark7: defaultAccentColors.dark7,
  darkA7: defaultAccentColors.darkA7,
  color8: `light-dark(${ defaultAccentColors.light8 }, ${ defaultAccentColors.dark8 })`,
  alpha8: `light-dark(${ defaultAccentColors.lightA8 }, ${ defaultAccentColors.darkA8 })`,
  light8: defaultAccentColors.light8,
  lightA8: defaultAccentColors.lightA8,
  dark8: defaultAccentColors.dark8,
  darkA8: defaultAccentColors.darkA8,
  color9: `light-dark(${ defaultAccentColors.light9 }, ${ defaultAccentColors.dark9 })`,
  alpha9: `light-dark(${ defaultAccentColors.lightA9 }, ${ defaultAccentColors.darkA9 })`,
  light9: defaultAccentColors.light9,
  lightA9: defaultAccentColors.lightA9,
  dark9: defaultAccentColors.dark9,
  darkA9: defaultAccentColors.darkA9,
  color10: `light-dark(${ defaultAccentColors.light10 }, ${ defaultAccentColors.dark10 })`,
  alpha10: `light-dark(${ defaultAccentColors.lightA10 }, ${ defaultAccentColors.darkA10 })`,
  light10: defaultAccentColors.light10,
  lightA10: defaultAccentColors.lightA10,
  dark10: defaultAccentColors.dark10,
  darkA10: defaultAccentColors.darkA10,
  color11: `light-dark(${ defaultAccentColors.light11 }, ${ defaultAccentColors.dark11 })`,
  alpha11: `light-dark(${ defaultAccentColors.lightA11 }, ${ defaultAccentColors.darkA11 })`,
  light11: defaultAccentColors.light11,
  lightA11: defaultAccentColors.lightA11,
  dark11: defaultAccentColors.dark11,
  darkA11: defaultAccentColors.darkA11,
  color12: `light-dark(${ defaultAccentColors.light12 }, ${ defaultAccentColors.dark12 })`,
  alpha12: `light-dark(${ defaultAccentColors.lightA12 }, ${ defaultAccentColors.darkA12 })`,
  light12: defaultAccentColors.light12,
  lightA12: defaultAccentColors.lightA12,
  dark12: defaultAccentColors.dark12,
  darkA12: defaultAccentColors.darkA12
});
