import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { negativeAccentColors } from '../../colors/accent/negative.stylex';

export const accentNegative = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ negativeAccentColors.light1 }, ${ negativeAccentColors.dark1 })`,
  alpha1: `light-dark(${ negativeAccentColors.lightA1 }, ${ negativeAccentColors.darkA1 })`,
  light1: negativeAccentColors.light1,
  lightA1: negativeAccentColors.lightA1,
  dark1: negativeAccentColors.dark1,
  darkA1: negativeAccentColors.darkA1,
  color2: `light-dark(${ negativeAccentColors.light2 }, ${ negativeAccentColors.dark2 })`,
  alpha2: `light-dark(${ negativeAccentColors.lightA2 }, ${ negativeAccentColors.darkA2 })`,
  light2: negativeAccentColors.light2,
  lightA2: negativeAccentColors.lightA2,
  dark2: negativeAccentColors.dark2,
  darkA2: negativeAccentColors.darkA2,
  color3: `light-dark(${ negativeAccentColors.light3 }, ${ negativeAccentColors.dark3 })`,
  alpha3: `light-dark(${ negativeAccentColors.lightA3 }, ${ negativeAccentColors.darkA3 })`,
  light3: negativeAccentColors.light3,
  lightA3: negativeAccentColors.lightA3,
  dark3: negativeAccentColors.dark3,
  darkA3: negativeAccentColors.darkA3,
  color4: `light-dark(${ negativeAccentColors.light4 }, ${ negativeAccentColors.dark4 })`,
  alpha4: `light-dark(${ negativeAccentColors.lightA4 }, ${ negativeAccentColors.darkA4 })`,
  light4: negativeAccentColors.light4,
  lightA4: negativeAccentColors.lightA4,
  dark4: negativeAccentColors.dark4,
  darkA4: negativeAccentColors.darkA4,
  color5: `light-dark(${ negativeAccentColors.light5 }, ${ negativeAccentColors.dark5 })`,
  alpha5: `light-dark(${ negativeAccentColors.lightA5 }, ${ negativeAccentColors.darkA5 })`,
  light5: negativeAccentColors.light5,
  lightA5: negativeAccentColors.lightA5,
  dark5: negativeAccentColors.dark5,
  darkA5: negativeAccentColors.darkA5,
  color6: `light-dark(${ negativeAccentColors.light6 }, ${ negativeAccentColors.dark6 })`,
  alpha6: `light-dark(${ negativeAccentColors.lightA6 }, ${ negativeAccentColors.darkA6 })`,
  light6: negativeAccentColors.light6,
  lightA6: negativeAccentColors.lightA6,
  dark6: negativeAccentColors.dark6,
  darkA6: negativeAccentColors.darkA6,
  color7: `light-dark(${ negativeAccentColors.light7 }, ${ negativeAccentColors.dark7 })`,
  alpha7: `light-dark(${ negativeAccentColors.lightA7 }, ${ negativeAccentColors.darkA7 })`,
  light7: negativeAccentColors.light7,
  lightA7: negativeAccentColors.lightA7,
  dark7: negativeAccentColors.dark7,
  darkA7: negativeAccentColors.darkA7,
  color8: `light-dark(${ negativeAccentColors.light8 }, ${ negativeAccentColors.dark8 })`,
  alpha8: `light-dark(${ negativeAccentColors.lightA8 }, ${ negativeAccentColors.darkA8 })`,
  light8: negativeAccentColors.light8,
  lightA8: negativeAccentColors.lightA8,
  dark8: negativeAccentColors.dark8,
  darkA8: negativeAccentColors.darkA8,
  color9: `light-dark(${ negativeAccentColors.light9 }, ${ negativeAccentColors.dark9 })`,
  alpha9: `light-dark(${ negativeAccentColors.lightA9 }, ${ negativeAccentColors.darkA9 })`,
  light9: negativeAccentColors.light9,
  lightA9: negativeAccentColors.lightA9,
  dark9: negativeAccentColors.dark9,
  darkA9: negativeAccentColors.darkA9,
  color10: `light-dark(${ negativeAccentColors.light10 }, ${ negativeAccentColors.dark10 })`,
  alpha10: `light-dark(${ negativeAccentColors.lightA10 }, ${ negativeAccentColors.darkA10 })`,
  light10: negativeAccentColors.light10,
  lightA10: negativeAccentColors.lightA10,
  dark10: negativeAccentColors.dark10,
  darkA10: negativeAccentColors.darkA10,
  color11: `light-dark(${ negativeAccentColors.light11 }, ${ negativeAccentColors.dark11 })`,
  alpha11: `light-dark(${ negativeAccentColors.lightA11 }, ${ negativeAccentColors.darkA11 })`,
  light11: negativeAccentColors.light11,
  lightA11: negativeAccentColors.lightA11,
  dark11: negativeAccentColors.dark11,
  darkA11: negativeAccentColors.darkA11,
  color12: `light-dark(${ negativeAccentColors.light12 }, ${ negativeAccentColors.dark12 })`,
  alpha12: `light-dark(${ negativeAccentColors.lightA12 }, ${ negativeAccentColors.darkA12 })`,
  light12: negativeAccentColors.light12,
  lightA12: negativeAccentColors.lightA12,
  dark12: negativeAccentColors.dark12,
  darkA12: negativeAccentColors.darkA12
});
