import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { positiveAccentColors } from '../../colors/accent/positive.stylex';

export const accentPositive = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ positiveAccentColors.light1 }, ${ positiveAccentColors.dark1 })`,
  alpha1: `light-dark(${ positiveAccentColors.lightA1 }, ${ positiveAccentColors.darkA1 })`,
  light1: positiveAccentColors.light1,
  lightA1: positiveAccentColors.lightA1,
  dark1: positiveAccentColors.dark1,
  darkA1: positiveAccentColors.darkA1,
  color2: `light-dark(${ positiveAccentColors.light2 }, ${ positiveAccentColors.dark2 })`,
  alpha2: `light-dark(${ positiveAccentColors.lightA2 }, ${ positiveAccentColors.darkA2 })`,
  light2: positiveAccentColors.light2,
  lightA2: positiveAccentColors.lightA2,
  dark2: positiveAccentColors.dark2,
  darkA2: positiveAccentColors.darkA2,
  color3: `light-dark(${ positiveAccentColors.light3 }, ${ positiveAccentColors.dark3 })`,
  alpha3: `light-dark(${ positiveAccentColors.lightA3 }, ${ positiveAccentColors.darkA3 })`,
  light3: positiveAccentColors.light3,
  lightA3: positiveAccentColors.lightA3,
  dark3: positiveAccentColors.dark3,
  darkA3: positiveAccentColors.darkA3,
  color4: `light-dark(${ positiveAccentColors.light4 }, ${ positiveAccentColors.dark4 })`,
  alpha4: `light-dark(${ positiveAccentColors.lightA4 }, ${ positiveAccentColors.darkA4 })`,
  light4: positiveAccentColors.light4,
  lightA4: positiveAccentColors.lightA4,
  dark4: positiveAccentColors.dark4,
  darkA4: positiveAccentColors.darkA4,
  color5: `light-dark(${ positiveAccentColors.light5 }, ${ positiveAccentColors.dark5 })`,
  alpha5: `light-dark(${ positiveAccentColors.lightA5 }, ${ positiveAccentColors.darkA5 })`,
  light5: positiveAccentColors.light5,
  lightA5: positiveAccentColors.lightA5,
  dark5: positiveAccentColors.dark5,
  darkA5: positiveAccentColors.darkA5,
  color6: `light-dark(${ positiveAccentColors.light6 }, ${ positiveAccentColors.dark6 })`,
  alpha6: `light-dark(${ positiveAccentColors.lightA6 }, ${ positiveAccentColors.darkA6 })`,
  light6: positiveAccentColors.light6,
  lightA6: positiveAccentColors.lightA6,
  dark6: positiveAccentColors.dark6,
  darkA6: positiveAccentColors.darkA6,
  color7: `light-dark(${ positiveAccentColors.light7 }, ${ positiveAccentColors.dark7 })`,
  alpha7: `light-dark(${ positiveAccentColors.lightA7 }, ${ positiveAccentColors.darkA7 })`,
  light7: positiveAccentColors.light7,
  lightA7: positiveAccentColors.lightA7,
  dark7: positiveAccentColors.dark7,
  darkA7: positiveAccentColors.darkA7,
  color8: `light-dark(${ positiveAccentColors.light8 }, ${ positiveAccentColors.dark8 })`,
  alpha8: `light-dark(${ positiveAccentColors.lightA8 }, ${ positiveAccentColors.darkA8 })`,
  light8: positiveAccentColors.light8,
  lightA8: positiveAccentColors.lightA8,
  dark8: positiveAccentColors.dark8,
  darkA8: positiveAccentColors.darkA8,
  color9: `light-dark(${ positiveAccentColors.light9 }, ${ positiveAccentColors.dark9 })`,
  alpha9: `light-dark(${ positiveAccentColors.lightA9 }, ${ positiveAccentColors.darkA9 })`,
  light9: positiveAccentColors.light9,
  lightA9: positiveAccentColors.lightA9,
  dark9: positiveAccentColors.dark9,
  darkA9: positiveAccentColors.darkA9,
  color10: `light-dark(${ positiveAccentColors.light10 }, ${ positiveAccentColors.dark10 })`,
  alpha10: `light-dark(${ positiveAccentColors.lightA10 }, ${ positiveAccentColors.darkA10 })`,
  light10: positiveAccentColors.light10,
  lightA10: positiveAccentColors.lightA10,
  dark10: positiveAccentColors.dark10,
  darkA10: positiveAccentColors.darkA10,
  color11: `light-dark(${ positiveAccentColors.light11 }, ${ positiveAccentColors.dark11 })`,
  alpha11: `light-dark(${ positiveAccentColors.lightA11 }, ${ positiveAccentColors.darkA11 })`,
  light11: positiveAccentColors.light11,
  lightA11: positiveAccentColors.lightA11,
  dark11: positiveAccentColors.dark11,
  darkA11: positiveAccentColors.darkA11,
  color12: `light-dark(${ positiveAccentColors.light12 }, ${ positiveAccentColors.dark12 })`,
  alpha12: `light-dark(${ positiveAccentColors.lightA12 }, ${ positiveAccentColors.darkA12 })`,
  light12: positiveAccentColors.light12,
  lightA12: positiveAccentColors.lightA12,
  dark12: positiveAccentColors.dark12,
  darkA12: positiveAccentColors.darkA12
});
