import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { primaryAccentColors } from '../../colors/accent/primary.stylex';

export const accentPrimary = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ primaryAccentColors.light1 }, ${ primaryAccentColors.dark1 })`,
  alpha1: `light-dark(${ primaryAccentColors.lightA1 }, ${ primaryAccentColors.darkA1 })`,
  light1: primaryAccentColors.light1,
  lightA1: primaryAccentColors.lightA1,
  dark1: primaryAccentColors.dark1,
  darkA1: primaryAccentColors.darkA1,
  color2: `light-dark(${ primaryAccentColors.light2 }, ${ primaryAccentColors.dark2 })`,
  alpha2: `light-dark(${ primaryAccentColors.lightA2 }, ${ primaryAccentColors.darkA2 })`,
  light2: primaryAccentColors.light2,
  lightA2: primaryAccentColors.lightA2,
  dark2: primaryAccentColors.dark2,
  darkA2: primaryAccentColors.darkA2,
  color3: `light-dark(${ primaryAccentColors.light3 }, ${ primaryAccentColors.dark3 })`,
  alpha3: `light-dark(${ primaryAccentColors.lightA3 }, ${ primaryAccentColors.darkA3 })`,
  light3: primaryAccentColors.light3,
  lightA3: primaryAccentColors.lightA3,
  dark3: primaryAccentColors.dark3,
  darkA3: primaryAccentColors.darkA3,
  color4: `light-dark(${ primaryAccentColors.light4 }, ${ primaryAccentColors.dark4 })`,
  alpha4: `light-dark(${ primaryAccentColors.lightA4 }, ${ primaryAccentColors.darkA4 })`,
  light4: primaryAccentColors.light4,
  lightA4: primaryAccentColors.lightA4,
  dark4: primaryAccentColors.dark4,
  darkA4: primaryAccentColors.darkA4,
  color5: `light-dark(${ primaryAccentColors.light5 }, ${ primaryAccentColors.dark5 })`,
  alpha5: `light-dark(${ primaryAccentColors.lightA5 }, ${ primaryAccentColors.darkA5 })`,
  light5: primaryAccentColors.light5,
  lightA5: primaryAccentColors.lightA5,
  dark5: primaryAccentColors.dark5,
  darkA5: primaryAccentColors.darkA5,
  color6: `light-dark(${ primaryAccentColors.light6 }, ${ primaryAccentColors.dark6 })`,
  alpha6: `light-dark(${ primaryAccentColors.lightA6 }, ${ primaryAccentColors.darkA6 })`,
  light6: primaryAccentColors.light6,
  lightA6: primaryAccentColors.lightA6,
  dark6: primaryAccentColors.dark6,
  darkA6: primaryAccentColors.darkA6,
  color7: `light-dark(${ primaryAccentColors.light7 }, ${ primaryAccentColors.dark7 })`,
  alpha7: `light-dark(${ primaryAccentColors.lightA7 }, ${ primaryAccentColors.darkA7 })`,
  light7: primaryAccentColors.light7,
  lightA7: primaryAccentColors.lightA7,
  dark7: primaryAccentColors.dark7,
  darkA7: primaryAccentColors.darkA7,
  color8: `light-dark(${ primaryAccentColors.light8 }, ${ primaryAccentColors.dark8 })`,
  alpha8: `light-dark(${ primaryAccentColors.lightA8 }, ${ primaryAccentColors.darkA8 })`,
  light8: primaryAccentColors.light8,
  lightA8: primaryAccentColors.lightA8,
  dark8: primaryAccentColors.dark8,
  darkA8: primaryAccentColors.darkA8,
  color9: `light-dark(${ primaryAccentColors.light9 }, ${ primaryAccentColors.dark9 })`,
  alpha9: `light-dark(${ primaryAccentColors.lightA9 }, ${ primaryAccentColors.darkA9 })`,
  light9: primaryAccentColors.light9,
  lightA9: primaryAccentColors.lightA9,
  dark9: primaryAccentColors.dark9,
  darkA9: primaryAccentColors.darkA9,
  color10: `light-dark(${ primaryAccentColors.light10 }, ${ primaryAccentColors.dark10 })`,
  alpha10: `light-dark(${ primaryAccentColors.lightA10 }, ${ primaryAccentColors.darkA10 })`,
  light10: primaryAccentColors.light10,
  lightA10: primaryAccentColors.lightA10,
  dark10: primaryAccentColors.dark10,
  darkA10: primaryAccentColors.darkA10,
  color11: `light-dark(${ primaryAccentColors.light11 }, ${ primaryAccentColors.dark11 })`,
  alpha11: `light-dark(${ primaryAccentColors.lightA11 }, ${ primaryAccentColors.darkA11 })`,
  light11: primaryAccentColors.light11,
  lightA11: primaryAccentColors.lightA11,
  dark11: primaryAccentColors.dark11,
  darkA11: primaryAccentColors.darkA11,
  color12: `light-dark(${ primaryAccentColors.light12 }, ${ primaryAccentColors.dark12 })`,
  alpha12: `light-dark(${ primaryAccentColors.lightA12 }, ${ primaryAccentColors.darkA12 })`,
  light12: primaryAccentColors.light12,
  lightA12: primaryAccentColors.lightA12,
  dark12: primaryAccentColors.dark12,
  darkA12: primaryAccentColors.darkA12
});
