import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { secondaryAccentColors } from '../../colors/accent/secondary.stylex';

export const accentSecondary = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ secondaryAccentColors.light1 }, ${ secondaryAccentColors.dark1 })`,
  alpha1: `light-dark(${ secondaryAccentColors.lightA1 }, ${ secondaryAccentColors.darkA1 })`,
  light1: secondaryAccentColors.light1,
  lightA1: secondaryAccentColors.lightA1,
  dark1: secondaryAccentColors.dark1,
  darkA1: secondaryAccentColors.darkA1,
  color2: `light-dark(${ secondaryAccentColors.light2 }, ${ secondaryAccentColors.dark2 })`,
  alpha2: `light-dark(${ secondaryAccentColors.lightA2 }, ${ secondaryAccentColors.darkA2 })`,
  light2: secondaryAccentColors.light2,
  lightA2: secondaryAccentColors.lightA2,
  dark2: secondaryAccentColors.dark2,
  darkA2: secondaryAccentColors.darkA2,
  color3: `light-dark(${ secondaryAccentColors.light3 }, ${ secondaryAccentColors.dark3 })`,
  alpha3: `light-dark(${ secondaryAccentColors.lightA3 }, ${ secondaryAccentColors.darkA3 })`,
  light3: secondaryAccentColors.light3,
  lightA3: secondaryAccentColors.lightA3,
  dark3: secondaryAccentColors.dark3,
  darkA3: secondaryAccentColors.darkA3,
  color4: `light-dark(${ secondaryAccentColors.light4 }, ${ secondaryAccentColors.dark4 })`,
  alpha4: `light-dark(${ secondaryAccentColors.lightA4 }, ${ secondaryAccentColors.darkA4 })`,
  light4: secondaryAccentColors.light4,
  lightA4: secondaryAccentColors.lightA4,
  dark4: secondaryAccentColors.dark4,
  darkA4: secondaryAccentColors.darkA4,
  color5: `light-dark(${ secondaryAccentColors.light5 }, ${ secondaryAccentColors.dark5 })`,
  alpha5: `light-dark(${ secondaryAccentColors.lightA5 }, ${ secondaryAccentColors.darkA5 })`,
  light5: secondaryAccentColors.light5,
  lightA5: secondaryAccentColors.lightA5,
  dark5: secondaryAccentColors.dark5,
  darkA5: secondaryAccentColors.darkA5,
  color6: `light-dark(${ secondaryAccentColors.light6 }, ${ secondaryAccentColors.dark6 })`,
  alpha6: `light-dark(${ secondaryAccentColors.lightA6 }, ${ secondaryAccentColors.darkA6 })`,
  light6: secondaryAccentColors.light6,
  lightA6: secondaryAccentColors.lightA6,
  dark6: secondaryAccentColors.dark6,
  darkA6: secondaryAccentColors.darkA6,
  color7: `light-dark(${ secondaryAccentColors.light7 }, ${ secondaryAccentColors.dark7 })`,
  alpha7: `light-dark(${ secondaryAccentColors.lightA7 }, ${ secondaryAccentColors.darkA7 })`,
  light7: secondaryAccentColors.light7,
  lightA7: secondaryAccentColors.lightA7,
  dark7: secondaryAccentColors.dark7,
  darkA7: secondaryAccentColors.darkA7,
  color8: `light-dark(${ secondaryAccentColors.light8 }, ${ secondaryAccentColors.dark8 })`,
  alpha8: `light-dark(${ secondaryAccentColors.lightA8 }, ${ secondaryAccentColors.darkA8 })`,
  light8: secondaryAccentColors.light8,
  lightA8: secondaryAccentColors.lightA8,
  dark8: secondaryAccentColors.dark8,
  darkA8: secondaryAccentColors.darkA8,
  color9: `light-dark(${ secondaryAccentColors.light9 }, ${ secondaryAccentColors.dark9 })`,
  alpha9: `light-dark(${ secondaryAccentColors.lightA9 }, ${ secondaryAccentColors.darkA9 })`,
  light9: secondaryAccentColors.light9,
  lightA9: secondaryAccentColors.lightA9,
  dark9: secondaryAccentColors.dark9,
  darkA9: secondaryAccentColors.darkA9,
  color10: `light-dark(${ secondaryAccentColors.light10 }, ${ secondaryAccentColors.dark10 })`,
  alpha10: `light-dark(${ secondaryAccentColors.lightA10 }, ${ secondaryAccentColors.darkA10 })`,
  light10: secondaryAccentColors.light10,
  lightA10: secondaryAccentColors.lightA10,
  dark10: secondaryAccentColors.dark10,
  darkA10: secondaryAccentColors.darkA10,
  color11: `light-dark(${ secondaryAccentColors.light11 }, ${ secondaryAccentColors.dark11 })`,
  alpha11: `light-dark(${ secondaryAccentColors.lightA11 }, ${ secondaryAccentColors.darkA11 })`,
  light11: secondaryAccentColors.light11,
  lightA11: secondaryAccentColors.lightA11,
  dark11: secondaryAccentColors.dark11,
  darkA11: secondaryAccentColors.darkA11,
  color12: `light-dark(${ secondaryAccentColors.light12 }, ${ secondaryAccentColors.dark12 })`,
  alpha12: `light-dark(${ secondaryAccentColors.lightA12 }, ${ secondaryAccentColors.darkA12 })`,
  light12: secondaryAccentColors.light12,
  lightA12: secondaryAccentColors.lightA12,
  dark12: secondaryAccentColors.dark12,
  darkA12: secondaryAccentColors.darkA12
});
