import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { tertiaryAccentColors } from '../../colors/accent/tertiary.stylex';

export const accentTertiary = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ tertiaryAccentColors.light1 }, ${ tertiaryAccentColors.dark1 })`,
  alpha1: `light-dark(${ tertiaryAccentColors.lightA1 }, ${ tertiaryAccentColors.darkA1 })`,
  light1: tertiaryAccentColors.light1,
  lightA1: tertiaryAccentColors.lightA1,
  dark1: tertiaryAccentColors.dark1,
  darkA1: tertiaryAccentColors.darkA1,
  color2: `light-dark(${ tertiaryAccentColors.light2 }, ${ tertiaryAccentColors.dark2 })`,
  alpha2: `light-dark(${ tertiaryAccentColors.lightA2 }, ${ tertiaryAccentColors.darkA2 })`,
  light2: tertiaryAccentColors.light2,
  lightA2: tertiaryAccentColors.lightA2,
  dark2: tertiaryAccentColors.dark2,
  darkA2: tertiaryAccentColors.darkA2,
  color3: `light-dark(${ tertiaryAccentColors.light3 }, ${ tertiaryAccentColors.dark3 })`,
  alpha3: `light-dark(${ tertiaryAccentColors.lightA3 }, ${ tertiaryAccentColors.darkA3 })`,
  light3: tertiaryAccentColors.light3,
  lightA3: tertiaryAccentColors.lightA3,
  dark3: tertiaryAccentColors.dark3,
  darkA3: tertiaryAccentColors.darkA3,
  color4: `light-dark(${ tertiaryAccentColors.light4 }, ${ tertiaryAccentColors.dark4 })`,
  alpha4: `light-dark(${ tertiaryAccentColors.lightA4 }, ${ tertiaryAccentColors.darkA4 })`,
  light4: tertiaryAccentColors.light4,
  lightA4: tertiaryAccentColors.lightA4,
  dark4: tertiaryAccentColors.dark4,
  darkA4: tertiaryAccentColors.darkA4,
  color5: `light-dark(${ tertiaryAccentColors.light5 }, ${ tertiaryAccentColors.dark5 })`,
  alpha5: `light-dark(${ tertiaryAccentColors.lightA5 }, ${ tertiaryAccentColors.darkA5 })`,
  light5: tertiaryAccentColors.light5,
  lightA5: tertiaryAccentColors.lightA5,
  dark5: tertiaryAccentColors.dark5,
  darkA5: tertiaryAccentColors.darkA5,
  color6: `light-dark(${ tertiaryAccentColors.light6 }, ${ tertiaryAccentColors.dark6 })`,
  alpha6: `light-dark(${ tertiaryAccentColors.lightA6 }, ${ tertiaryAccentColors.darkA6 })`,
  light6: tertiaryAccentColors.light6,
  lightA6: tertiaryAccentColors.lightA6,
  dark6: tertiaryAccentColors.dark6,
  darkA6: tertiaryAccentColors.darkA6,
  color7: `light-dark(${ tertiaryAccentColors.light7 }, ${ tertiaryAccentColors.dark7 })`,
  alpha7: `light-dark(${ tertiaryAccentColors.lightA7 }, ${ tertiaryAccentColors.darkA7 })`,
  light7: tertiaryAccentColors.light7,
  lightA7: tertiaryAccentColors.lightA7,
  dark7: tertiaryAccentColors.dark7,
  darkA7: tertiaryAccentColors.darkA7,
  color8: `light-dark(${ tertiaryAccentColors.light8 }, ${ tertiaryAccentColors.dark8 })`,
  alpha8: `light-dark(${ tertiaryAccentColors.lightA8 }, ${ tertiaryAccentColors.darkA8 })`,
  light8: tertiaryAccentColors.light8,
  lightA8: tertiaryAccentColors.lightA8,
  dark8: tertiaryAccentColors.dark8,
  darkA8: tertiaryAccentColors.darkA8,
  color9: `light-dark(${ tertiaryAccentColors.light9 }, ${ tertiaryAccentColors.dark9 })`,
  alpha9: `light-dark(${ tertiaryAccentColors.lightA9 }, ${ tertiaryAccentColors.darkA9 })`,
  light9: tertiaryAccentColors.light9,
  lightA9: tertiaryAccentColors.lightA9,
  dark9: tertiaryAccentColors.dark9,
  darkA9: tertiaryAccentColors.darkA9,
  color10: `light-dark(${ tertiaryAccentColors.light10 }, ${ tertiaryAccentColors.dark10 })`,
  alpha10: `light-dark(${ tertiaryAccentColors.lightA10 }, ${ tertiaryAccentColors.darkA10 })`,
  light10: tertiaryAccentColors.light10,
  lightA10: tertiaryAccentColors.lightA10,
  dark10: tertiaryAccentColors.dark10,
  darkA10: tertiaryAccentColors.darkA10,
  color11: `light-dark(${ tertiaryAccentColors.light11 }, ${ tertiaryAccentColors.dark11 })`,
  alpha11: `light-dark(${ tertiaryAccentColors.lightA11 }, ${ tertiaryAccentColors.darkA11 })`,
  light11: tertiaryAccentColors.light11,
  lightA11: tertiaryAccentColors.lightA11,
  dark11: tertiaryAccentColors.dark11,
  darkA11: tertiaryAccentColors.darkA11,
  color12: `light-dark(${ tertiaryAccentColors.light12 }, ${ tertiaryAccentColors.dark12 })`,
  alpha12: `light-dark(${ tertiaryAccentColors.lightA12 }, ${ tertiaryAccentColors.darkA12 })`,
  light12: tertiaryAccentColors.light12,
  lightA12: tertiaryAccentColors.lightA12,
  dark12: tertiaryAccentColors.dark12,
  darkA12: tertiaryAccentColors.darkA12
});
