import * as stylex from '@stylexjs/stylex';
import { radixAccent } from '../../radix.stylex';
import { warningAccentColors } from '../../colors/accent/warning.stylex';

export const accentWarning = stylex.createTheme(radixAccent, {
  color1: `light-dark(${ warningAccentColors.light1 }, ${ warningAccentColors.dark1 })`,
  alpha1: `light-dark(${ warningAccentColors.lightA1 }, ${ warningAccentColors.darkA1 })`,
  light1: warningAccentColors.light1,
  lightA1: warningAccentColors.lightA1,
  dark1: warningAccentColors.dark1,
  darkA1: warningAccentColors.darkA1,
  color2: `light-dark(${ warningAccentColors.light2 }, ${ warningAccentColors.dark2 })`,
  alpha2: `light-dark(${ warningAccentColors.lightA2 }, ${ warningAccentColors.darkA2 })`,
  light2: warningAccentColors.light2,
  lightA2: warningAccentColors.lightA2,
  dark2: warningAccentColors.dark2,
  darkA2: warningAccentColors.darkA2,
  color3: `light-dark(${ warningAccentColors.light3 }, ${ warningAccentColors.dark3 })`,
  alpha3: `light-dark(${ warningAccentColors.lightA3 }, ${ warningAccentColors.darkA3 })`,
  light3: warningAccentColors.light3,
  lightA3: warningAccentColors.lightA3,
  dark3: warningAccentColors.dark3,
  darkA3: warningAccentColors.darkA3,
  color4: `light-dark(${ warningAccentColors.light4 }, ${ warningAccentColors.dark4 })`,
  alpha4: `light-dark(${ warningAccentColors.lightA4 }, ${ warningAccentColors.darkA4 })`,
  light4: warningAccentColors.light4,
  lightA4: warningAccentColors.lightA4,
  dark4: warningAccentColors.dark4,
  darkA4: warningAccentColors.darkA4,
  color5: `light-dark(${ warningAccentColors.light5 }, ${ warningAccentColors.dark5 })`,
  alpha5: `light-dark(${ warningAccentColors.lightA5 }, ${ warningAccentColors.darkA5 })`,
  light5: warningAccentColors.light5,
  lightA5: warningAccentColors.lightA5,
  dark5: warningAccentColors.dark5,
  darkA5: warningAccentColors.darkA5,
  color6: `light-dark(${ warningAccentColors.light6 }, ${ warningAccentColors.dark6 })`,
  alpha6: `light-dark(${ warningAccentColors.lightA6 }, ${ warningAccentColors.darkA6 })`,
  light6: warningAccentColors.light6,
  lightA6: warningAccentColors.lightA6,
  dark6: warningAccentColors.dark6,
  darkA6: warningAccentColors.darkA6,
  color7: `light-dark(${ warningAccentColors.light7 }, ${ warningAccentColors.dark7 })`,
  alpha7: `light-dark(${ warningAccentColors.lightA7 }, ${ warningAccentColors.darkA7 })`,
  light7: warningAccentColors.light7,
  lightA7: warningAccentColors.lightA7,
  dark7: warningAccentColors.dark7,
  darkA7: warningAccentColors.darkA7,
  color8: `light-dark(${ warningAccentColors.light8 }, ${ warningAccentColors.dark8 })`,
  alpha8: `light-dark(${ warningAccentColors.lightA8 }, ${ warningAccentColors.darkA8 })`,
  light8: warningAccentColors.light8,
  lightA8: warningAccentColors.lightA8,
  dark8: warningAccentColors.dark8,
  darkA8: warningAccentColors.darkA8,
  color9: `light-dark(${ warningAccentColors.light9 }, ${ warningAccentColors.dark9 })`,
  alpha9: `light-dark(${ warningAccentColors.lightA9 }, ${ warningAccentColors.darkA9 })`,
  light9: warningAccentColors.light9,
  lightA9: warningAccentColors.lightA9,
  dark9: warningAccentColors.dark9,
  darkA9: warningAccentColors.darkA9,
  color10: `light-dark(${ warningAccentColors.light10 }, ${ warningAccentColors.dark10 })`,
  alpha10: `light-dark(${ warningAccentColors.lightA10 }, ${ warningAccentColors.darkA10 })`,
  light10: warningAccentColors.light10,
  lightA10: warningAccentColors.lightA10,
  dark10: warningAccentColors.dark10,
  darkA10: warningAccentColors.darkA10,
  color11: `light-dark(${ warningAccentColors.light11 }, ${ warningAccentColors.dark11 })`,
  alpha11: `light-dark(${ warningAccentColors.lightA11 }, ${ warningAccentColors.darkA11 })`,
  light11: warningAccentColors.light11,
  lightA11: warningAccentColors.lightA11,
  dark11: warningAccentColors.dark11,
  darkA11: warningAccentColors.darkA11,
  color12: `light-dark(${ warningAccentColors.light12 }, ${ warningAccentColors.dark12 })`,
  alpha12: `light-dark(${ warningAccentColors.lightA12 }, ${ warningAccentColors.darkA12 })`,
  light12: warningAccentColors.light12,
  lightA12: warningAccentColors.lightA12,
  dark12: warningAccentColors.dark12,
  darkA12: warningAccentColors.darkA12
});
