import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { defaultSurfaceColors } from '../../colors/surface/default.stylex';

export const surfaceDefault = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ defaultSurfaceColors.light1 }, ${ defaultSurfaceColors.dark1 })`,
  alpha1: `light-dark(${ defaultSurfaceColors.lightA1 }, ${ defaultSurfaceColors.darkA1 })`,
  light1: defaultSurfaceColors.light1,
  lightA1: defaultSurfaceColors.lightA1,
  dark1: defaultSurfaceColors.dark1,
  darkA1: defaultSurfaceColors.darkA1,
  color2: `light-dark(${ defaultSurfaceColors.light2 }, ${ defaultSurfaceColors.dark2 })`,
  alpha2: `light-dark(${ defaultSurfaceColors.lightA2 }, ${ defaultSurfaceColors.darkA2 })`,
  light2: defaultSurfaceColors.light2,
  lightA2: defaultSurfaceColors.lightA2,
  dark2: defaultSurfaceColors.dark2,
  darkA2: defaultSurfaceColors.darkA2,
  color3: `light-dark(${ defaultSurfaceColors.light3 }, ${ defaultSurfaceColors.dark3 })`,
  alpha3: `light-dark(${ defaultSurfaceColors.lightA3 }, ${ defaultSurfaceColors.darkA3 })`,
  light3: defaultSurfaceColors.light3,
  lightA3: defaultSurfaceColors.lightA3,
  dark3: defaultSurfaceColors.dark3,
  darkA3: defaultSurfaceColors.darkA3,
  color4: `light-dark(${ defaultSurfaceColors.light4 }, ${ defaultSurfaceColors.dark4 })`,
  alpha4: `light-dark(${ defaultSurfaceColors.lightA4 }, ${ defaultSurfaceColors.darkA4 })`,
  light4: defaultSurfaceColors.light4,
  lightA4: defaultSurfaceColors.lightA4,
  dark4: defaultSurfaceColors.dark4,
  darkA4: defaultSurfaceColors.darkA4,
  color5: `light-dark(${ defaultSurfaceColors.light5 }, ${ defaultSurfaceColors.dark5 })`,
  alpha5: `light-dark(${ defaultSurfaceColors.lightA5 }, ${ defaultSurfaceColors.darkA5 })`,
  light5: defaultSurfaceColors.light5,
  lightA5: defaultSurfaceColors.lightA5,
  dark5: defaultSurfaceColors.dark5,
  darkA5: defaultSurfaceColors.darkA5,
  color6: `light-dark(${ defaultSurfaceColors.light6 }, ${ defaultSurfaceColors.dark6 })`,
  alpha6: `light-dark(${ defaultSurfaceColors.lightA6 }, ${ defaultSurfaceColors.darkA6 })`,
  light6: defaultSurfaceColors.light6,
  lightA6: defaultSurfaceColors.lightA6,
  dark6: defaultSurfaceColors.dark6,
  darkA6: defaultSurfaceColors.darkA6,
  color7: `light-dark(${ defaultSurfaceColors.light7 }, ${ defaultSurfaceColors.dark7 })`,
  alpha7: `light-dark(${ defaultSurfaceColors.lightA7 }, ${ defaultSurfaceColors.darkA7 })`,
  light7: defaultSurfaceColors.light7,
  lightA7: defaultSurfaceColors.lightA7,
  dark7: defaultSurfaceColors.dark7,
  darkA7: defaultSurfaceColors.darkA7,
  color8: `light-dark(${ defaultSurfaceColors.light8 }, ${ defaultSurfaceColors.dark8 })`,
  alpha8: `light-dark(${ defaultSurfaceColors.lightA8 }, ${ defaultSurfaceColors.darkA8 })`,
  light8: defaultSurfaceColors.light8,
  lightA8: defaultSurfaceColors.lightA8,
  dark8: defaultSurfaceColors.dark8,
  darkA8: defaultSurfaceColors.darkA8,
  color9: `light-dark(${ defaultSurfaceColors.light9 }, ${ defaultSurfaceColors.dark9 })`,
  alpha9: `light-dark(${ defaultSurfaceColors.lightA9 }, ${ defaultSurfaceColors.darkA9 })`,
  light9: defaultSurfaceColors.light9,
  lightA9: defaultSurfaceColors.lightA9,
  dark9: defaultSurfaceColors.dark9,
  darkA9: defaultSurfaceColors.darkA9,
  color10: `light-dark(${ defaultSurfaceColors.light10 }, ${ defaultSurfaceColors.dark10 })`,
  alpha10: `light-dark(${ defaultSurfaceColors.lightA10 }, ${ defaultSurfaceColors.darkA10 })`,
  light10: defaultSurfaceColors.light10,
  lightA10: defaultSurfaceColors.lightA10,
  dark10: defaultSurfaceColors.dark10,
  darkA10: defaultSurfaceColors.darkA10,
  color11: `light-dark(${ defaultSurfaceColors.light11 }, ${ defaultSurfaceColors.dark11 })`,
  alpha11: `light-dark(${ defaultSurfaceColors.lightA11 }, ${ defaultSurfaceColors.darkA11 })`,
  light11: defaultSurfaceColors.light11,
  lightA11: defaultSurfaceColors.lightA11,
  dark11: defaultSurfaceColors.dark11,
  darkA11: defaultSurfaceColors.darkA11,
  color12: `light-dark(${ defaultSurfaceColors.light12 }, ${ defaultSurfaceColors.dark12 })`,
  alpha12: `light-dark(${ defaultSurfaceColors.lightA12 }, ${ defaultSurfaceColors.darkA12 })`,
  light12: defaultSurfaceColors.light12,
  lightA12: defaultSurfaceColors.lightA12,
  dark12: defaultSurfaceColors.dark12,
  darkA12: defaultSurfaceColors.darkA12
});
