import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { negativeSurfaceColors } from '../../colors/surface/negative.stylex';

export const surfaceNegative = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ negativeSurfaceColors.light1 }, ${ negativeSurfaceColors.dark1 })`,
  alpha1: `light-dark(${ negativeSurfaceColors.lightA1 }, ${ negativeSurfaceColors.darkA1 })`,
  light1: negativeSurfaceColors.light1,
  lightA1: negativeSurfaceColors.lightA1,
  dark1: negativeSurfaceColors.dark1,
  darkA1: negativeSurfaceColors.darkA1,
  color2: `light-dark(${ negativeSurfaceColors.light2 }, ${ negativeSurfaceColors.dark2 })`,
  alpha2: `light-dark(${ negativeSurfaceColors.lightA2 }, ${ negativeSurfaceColors.darkA2 })`,
  light2: negativeSurfaceColors.light2,
  lightA2: negativeSurfaceColors.lightA2,
  dark2: negativeSurfaceColors.dark2,
  darkA2: negativeSurfaceColors.darkA2,
  color3: `light-dark(${ negativeSurfaceColors.light3 }, ${ negativeSurfaceColors.dark3 })`,
  alpha3: `light-dark(${ negativeSurfaceColors.lightA3 }, ${ negativeSurfaceColors.darkA3 })`,
  light3: negativeSurfaceColors.light3,
  lightA3: negativeSurfaceColors.lightA3,
  dark3: negativeSurfaceColors.dark3,
  darkA3: negativeSurfaceColors.darkA3,
  color4: `light-dark(${ negativeSurfaceColors.light4 }, ${ negativeSurfaceColors.dark4 })`,
  alpha4: `light-dark(${ negativeSurfaceColors.lightA4 }, ${ negativeSurfaceColors.darkA4 })`,
  light4: negativeSurfaceColors.light4,
  lightA4: negativeSurfaceColors.lightA4,
  dark4: negativeSurfaceColors.dark4,
  darkA4: negativeSurfaceColors.darkA4,
  color5: `light-dark(${ negativeSurfaceColors.light5 }, ${ negativeSurfaceColors.dark5 })`,
  alpha5: `light-dark(${ negativeSurfaceColors.lightA5 }, ${ negativeSurfaceColors.darkA5 })`,
  light5: negativeSurfaceColors.light5,
  lightA5: negativeSurfaceColors.lightA5,
  dark5: negativeSurfaceColors.dark5,
  darkA5: negativeSurfaceColors.darkA5,
  color6: `light-dark(${ negativeSurfaceColors.light6 }, ${ negativeSurfaceColors.dark6 })`,
  alpha6: `light-dark(${ negativeSurfaceColors.lightA6 }, ${ negativeSurfaceColors.darkA6 })`,
  light6: negativeSurfaceColors.light6,
  lightA6: negativeSurfaceColors.lightA6,
  dark6: negativeSurfaceColors.dark6,
  darkA6: negativeSurfaceColors.darkA6,
  color7: `light-dark(${ negativeSurfaceColors.light7 }, ${ negativeSurfaceColors.dark7 })`,
  alpha7: `light-dark(${ negativeSurfaceColors.lightA7 }, ${ negativeSurfaceColors.darkA7 })`,
  light7: negativeSurfaceColors.light7,
  lightA7: negativeSurfaceColors.lightA7,
  dark7: negativeSurfaceColors.dark7,
  darkA7: negativeSurfaceColors.darkA7,
  color8: `light-dark(${ negativeSurfaceColors.light8 }, ${ negativeSurfaceColors.dark8 })`,
  alpha8: `light-dark(${ negativeSurfaceColors.lightA8 }, ${ negativeSurfaceColors.darkA8 })`,
  light8: negativeSurfaceColors.light8,
  lightA8: negativeSurfaceColors.lightA8,
  dark8: negativeSurfaceColors.dark8,
  darkA8: negativeSurfaceColors.darkA8,
  color9: `light-dark(${ negativeSurfaceColors.light9 }, ${ negativeSurfaceColors.dark9 })`,
  alpha9: `light-dark(${ negativeSurfaceColors.lightA9 }, ${ negativeSurfaceColors.darkA9 })`,
  light9: negativeSurfaceColors.light9,
  lightA9: negativeSurfaceColors.lightA9,
  dark9: negativeSurfaceColors.dark9,
  darkA9: negativeSurfaceColors.darkA9,
  color10: `light-dark(${ negativeSurfaceColors.light10 }, ${ negativeSurfaceColors.dark10 })`,
  alpha10: `light-dark(${ negativeSurfaceColors.lightA10 }, ${ negativeSurfaceColors.darkA10 })`,
  light10: negativeSurfaceColors.light10,
  lightA10: negativeSurfaceColors.lightA10,
  dark10: negativeSurfaceColors.dark10,
  darkA10: negativeSurfaceColors.darkA10,
  color11: `light-dark(${ negativeSurfaceColors.light11 }, ${ negativeSurfaceColors.dark11 })`,
  alpha11: `light-dark(${ negativeSurfaceColors.lightA11 }, ${ negativeSurfaceColors.darkA11 })`,
  light11: negativeSurfaceColors.light11,
  lightA11: negativeSurfaceColors.lightA11,
  dark11: negativeSurfaceColors.dark11,
  darkA11: negativeSurfaceColors.darkA11,
  color12: `light-dark(${ negativeSurfaceColors.light12 }, ${ negativeSurfaceColors.dark12 })`,
  alpha12: `light-dark(${ negativeSurfaceColors.lightA12 }, ${ negativeSurfaceColors.darkA12 })`,
  light12: negativeSurfaceColors.light12,
  lightA12: negativeSurfaceColors.lightA12,
  dark12: negativeSurfaceColors.dark12,
  darkA12: negativeSurfaceColors.darkA12
});
