import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { positiveSurfaceColors } from '../../colors/surface/positive.stylex';

export const surfacePositive = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ positiveSurfaceColors.light1 }, ${ positiveSurfaceColors.dark1 })`,
  alpha1: `light-dark(${ positiveSurfaceColors.lightA1 }, ${ positiveSurfaceColors.darkA1 })`,
  light1: positiveSurfaceColors.light1,
  lightA1: positiveSurfaceColors.lightA1,
  dark1: positiveSurfaceColors.dark1,
  darkA1: positiveSurfaceColors.darkA1,
  color2: `light-dark(${ positiveSurfaceColors.light2 }, ${ positiveSurfaceColors.dark2 })`,
  alpha2: `light-dark(${ positiveSurfaceColors.lightA2 }, ${ positiveSurfaceColors.darkA2 })`,
  light2: positiveSurfaceColors.light2,
  lightA2: positiveSurfaceColors.lightA2,
  dark2: positiveSurfaceColors.dark2,
  darkA2: positiveSurfaceColors.darkA2,
  color3: `light-dark(${ positiveSurfaceColors.light3 }, ${ positiveSurfaceColors.dark3 })`,
  alpha3: `light-dark(${ positiveSurfaceColors.lightA3 }, ${ positiveSurfaceColors.darkA3 })`,
  light3: positiveSurfaceColors.light3,
  lightA3: positiveSurfaceColors.lightA3,
  dark3: positiveSurfaceColors.dark3,
  darkA3: positiveSurfaceColors.darkA3,
  color4: `light-dark(${ positiveSurfaceColors.light4 }, ${ positiveSurfaceColors.dark4 })`,
  alpha4: `light-dark(${ positiveSurfaceColors.lightA4 }, ${ positiveSurfaceColors.darkA4 })`,
  light4: positiveSurfaceColors.light4,
  lightA4: positiveSurfaceColors.lightA4,
  dark4: positiveSurfaceColors.dark4,
  darkA4: positiveSurfaceColors.darkA4,
  color5: `light-dark(${ positiveSurfaceColors.light5 }, ${ positiveSurfaceColors.dark5 })`,
  alpha5: `light-dark(${ positiveSurfaceColors.lightA5 }, ${ positiveSurfaceColors.darkA5 })`,
  light5: positiveSurfaceColors.light5,
  lightA5: positiveSurfaceColors.lightA5,
  dark5: positiveSurfaceColors.dark5,
  darkA5: positiveSurfaceColors.darkA5,
  color6: `light-dark(${ positiveSurfaceColors.light6 }, ${ positiveSurfaceColors.dark6 })`,
  alpha6: `light-dark(${ positiveSurfaceColors.lightA6 }, ${ positiveSurfaceColors.darkA6 })`,
  light6: positiveSurfaceColors.light6,
  lightA6: positiveSurfaceColors.lightA6,
  dark6: positiveSurfaceColors.dark6,
  darkA6: positiveSurfaceColors.darkA6,
  color7: `light-dark(${ positiveSurfaceColors.light7 }, ${ positiveSurfaceColors.dark7 })`,
  alpha7: `light-dark(${ positiveSurfaceColors.lightA7 }, ${ positiveSurfaceColors.darkA7 })`,
  light7: positiveSurfaceColors.light7,
  lightA7: positiveSurfaceColors.lightA7,
  dark7: positiveSurfaceColors.dark7,
  darkA7: positiveSurfaceColors.darkA7,
  color8: `light-dark(${ positiveSurfaceColors.light8 }, ${ positiveSurfaceColors.dark8 })`,
  alpha8: `light-dark(${ positiveSurfaceColors.lightA8 }, ${ positiveSurfaceColors.darkA8 })`,
  light8: positiveSurfaceColors.light8,
  lightA8: positiveSurfaceColors.lightA8,
  dark8: positiveSurfaceColors.dark8,
  darkA8: positiveSurfaceColors.darkA8,
  color9: `light-dark(${ positiveSurfaceColors.light9 }, ${ positiveSurfaceColors.dark9 })`,
  alpha9: `light-dark(${ positiveSurfaceColors.lightA9 }, ${ positiveSurfaceColors.darkA9 })`,
  light9: positiveSurfaceColors.light9,
  lightA9: positiveSurfaceColors.lightA9,
  dark9: positiveSurfaceColors.dark9,
  darkA9: positiveSurfaceColors.darkA9,
  color10: `light-dark(${ positiveSurfaceColors.light10 }, ${ positiveSurfaceColors.dark10 })`,
  alpha10: `light-dark(${ positiveSurfaceColors.lightA10 }, ${ positiveSurfaceColors.darkA10 })`,
  light10: positiveSurfaceColors.light10,
  lightA10: positiveSurfaceColors.lightA10,
  dark10: positiveSurfaceColors.dark10,
  darkA10: positiveSurfaceColors.darkA10,
  color11: `light-dark(${ positiveSurfaceColors.light11 }, ${ positiveSurfaceColors.dark11 })`,
  alpha11: `light-dark(${ positiveSurfaceColors.lightA11 }, ${ positiveSurfaceColors.darkA11 })`,
  light11: positiveSurfaceColors.light11,
  lightA11: positiveSurfaceColors.lightA11,
  dark11: positiveSurfaceColors.dark11,
  darkA11: positiveSurfaceColors.darkA11,
  color12: `light-dark(${ positiveSurfaceColors.light12 }, ${ positiveSurfaceColors.dark12 })`,
  alpha12: `light-dark(${ positiveSurfaceColors.lightA12 }, ${ positiveSurfaceColors.darkA12 })`,
  light12: positiveSurfaceColors.light12,
  lightA12: positiveSurfaceColors.lightA12,
  dark12: positiveSurfaceColors.dark12,
  darkA12: positiveSurfaceColors.darkA12
});
