import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { primarySurfaceColors } from '../../colors/surface/primary.stylex';

export const surfacePrimary = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ primarySurfaceColors.light1 }, ${ primarySurfaceColors.dark1 })`,
  alpha1: `light-dark(${ primarySurfaceColors.lightA1 }, ${ primarySurfaceColors.darkA1 })`,
  light1: primarySurfaceColors.light1,
  lightA1: primarySurfaceColors.lightA1,
  dark1: primarySurfaceColors.dark1,
  darkA1: primarySurfaceColors.darkA1,
  color2: `light-dark(${ primarySurfaceColors.light2 }, ${ primarySurfaceColors.dark2 })`,
  alpha2: `light-dark(${ primarySurfaceColors.lightA2 }, ${ primarySurfaceColors.darkA2 })`,
  light2: primarySurfaceColors.light2,
  lightA2: primarySurfaceColors.lightA2,
  dark2: primarySurfaceColors.dark2,
  darkA2: primarySurfaceColors.darkA2,
  color3: `light-dark(${ primarySurfaceColors.light3 }, ${ primarySurfaceColors.dark3 })`,
  alpha3: `light-dark(${ primarySurfaceColors.lightA3 }, ${ primarySurfaceColors.darkA3 })`,
  light3: primarySurfaceColors.light3,
  lightA3: primarySurfaceColors.lightA3,
  dark3: primarySurfaceColors.dark3,
  darkA3: primarySurfaceColors.darkA3,
  color4: `light-dark(${ primarySurfaceColors.light4 }, ${ primarySurfaceColors.dark4 })`,
  alpha4: `light-dark(${ primarySurfaceColors.lightA4 }, ${ primarySurfaceColors.darkA4 })`,
  light4: primarySurfaceColors.light4,
  lightA4: primarySurfaceColors.lightA4,
  dark4: primarySurfaceColors.dark4,
  darkA4: primarySurfaceColors.darkA4,
  color5: `light-dark(${ primarySurfaceColors.light5 }, ${ primarySurfaceColors.dark5 })`,
  alpha5: `light-dark(${ primarySurfaceColors.lightA5 }, ${ primarySurfaceColors.darkA5 })`,
  light5: primarySurfaceColors.light5,
  lightA5: primarySurfaceColors.lightA5,
  dark5: primarySurfaceColors.dark5,
  darkA5: primarySurfaceColors.darkA5,
  color6: `light-dark(${ primarySurfaceColors.light6 }, ${ primarySurfaceColors.dark6 })`,
  alpha6: `light-dark(${ primarySurfaceColors.lightA6 }, ${ primarySurfaceColors.darkA6 })`,
  light6: primarySurfaceColors.light6,
  lightA6: primarySurfaceColors.lightA6,
  dark6: primarySurfaceColors.dark6,
  darkA6: primarySurfaceColors.darkA6,
  color7: `light-dark(${ primarySurfaceColors.light7 }, ${ primarySurfaceColors.dark7 })`,
  alpha7: `light-dark(${ primarySurfaceColors.lightA7 }, ${ primarySurfaceColors.darkA7 })`,
  light7: primarySurfaceColors.light7,
  lightA7: primarySurfaceColors.lightA7,
  dark7: primarySurfaceColors.dark7,
  darkA7: primarySurfaceColors.darkA7,
  color8: `light-dark(${ primarySurfaceColors.light8 }, ${ primarySurfaceColors.dark8 })`,
  alpha8: `light-dark(${ primarySurfaceColors.lightA8 }, ${ primarySurfaceColors.darkA8 })`,
  light8: primarySurfaceColors.light8,
  lightA8: primarySurfaceColors.lightA8,
  dark8: primarySurfaceColors.dark8,
  darkA8: primarySurfaceColors.darkA8,
  color9: `light-dark(${ primarySurfaceColors.light9 }, ${ primarySurfaceColors.dark9 })`,
  alpha9: `light-dark(${ primarySurfaceColors.lightA9 }, ${ primarySurfaceColors.darkA9 })`,
  light9: primarySurfaceColors.light9,
  lightA9: primarySurfaceColors.lightA9,
  dark9: primarySurfaceColors.dark9,
  darkA9: primarySurfaceColors.darkA9,
  color10: `light-dark(${ primarySurfaceColors.light10 }, ${ primarySurfaceColors.dark10 })`,
  alpha10: `light-dark(${ primarySurfaceColors.lightA10 }, ${ primarySurfaceColors.darkA10 })`,
  light10: primarySurfaceColors.light10,
  lightA10: primarySurfaceColors.lightA10,
  dark10: primarySurfaceColors.dark10,
  darkA10: primarySurfaceColors.darkA10,
  color11: `light-dark(${ primarySurfaceColors.light11 }, ${ primarySurfaceColors.dark11 })`,
  alpha11: `light-dark(${ primarySurfaceColors.lightA11 }, ${ primarySurfaceColors.darkA11 })`,
  light11: primarySurfaceColors.light11,
  lightA11: primarySurfaceColors.lightA11,
  dark11: primarySurfaceColors.dark11,
  darkA11: primarySurfaceColors.darkA11,
  color12: `light-dark(${ primarySurfaceColors.light12 }, ${ primarySurfaceColors.dark12 })`,
  alpha12: `light-dark(${ primarySurfaceColors.lightA12 }, ${ primarySurfaceColors.darkA12 })`,
  light12: primarySurfaceColors.light12,
  lightA12: primarySurfaceColors.lightA12,
  dark12: primarySurfaceColors.dark12,
  darkA12: primarySurfaceColors.darkA12
});
