import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { secondarySurfaceColors } from '../../colors/surface/secondary.stylex';

export const surfaceSecondary = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ secondarySurfaceColors.light1 }, ${ secondarySurfaceColors.dark1 })`,
  alpha1: `light-dark(${ secondarySurfaceColors.lightA1 }, ${ secondarySurfaceColors.darkA1 })`,
  light1: secondarySurfaceColors.light1,
  lightA1: secondarySurfaceColors.lightA1,
  dark1: secondarySurfaceColors.dark1,
  darkA1: secondarySurfaceColors.darkA1,
  color2: `light-dark(${ secondarySurfaceColors.light2 }, ${ secondarySurfaceColors.dark2 })`,
  alpha2: `light-dark(${ secondarySurfaceColors.lightA2 }, ${ secondarySurfaceColors.darkA2 })`,
  light2: secondarySurfaceColors.light2,
  lightA2: secondarySurfaceColors.lightA2,
  dark2: secondarySurfaceColors.dark2,
  darkA2: secondarySurfaceColors.darkA2,
  color3: `light-dark(${ secondarySurfaceColors.light3 }, ${ secondarySurfaceColors.dark3 })`,
  alpha3: `light-dark(${ secondarySurfaceColors.lightA3 }, ${ secondarySurfaceColors.darkA3 })`,
  light3: secondarySurfaceColors.light3,
  lightA3: secondarySurfaceColors.lightA3,
  dark3: secondarySurfaceColors.dark3,
  darkA3: secondarySurfaceColors.darkA3,
  color4: `light-dark(${ secondarySurfaceColors.light4 }, ${ secondarySurfaceColors.dark4 })`,
  alpha4: `light-dark(${ secondarySurfaceColors.lightA4 }, ${ secondarySurfaceColors.darkA4 })`,
  light4: secondarySurfaceColors.light4,
  lightA4: secondarySurfaceColors.lightA4,
  dark4: secondarySurfaceColors.dark4,
  darkA4: secondarySurfaceColors.darkA4,
  color5: `light-dark(${ secondarySurfaceColors.light5 }, ${ secondarySurfaceColors.dark5 })`,
  alpha5: `light-dark(${ secondarySurfaceColors.lightA5 }, ${ secondarySurfaceColors.darkA5 })`,
  light5: secondarySurfaceColors.light5,
  lightA5: secondarySurfaceColors.lightA5,
  dark5: secondarySurfaceColors.dark5,
  darkA5: secondarySurfaceColors.darkA5,
  color6: `light-dark(${ secondarySurfaceColors.light6 }, ${ secondarySurfaceColors.dark6 })`,
  alpha6: `light-dark(${ secondarySurfaceColors.lightA6 }, ${ secondarySurfaceColors.darkA6 })`,
  light6: secondarySurfaceColors.light6,
  lightA6: secondarySurfaceColors.lightA6,
  dark6: secondarySurfaceColors.dark6,
  darkA6: secondarySurfaceColors.darkA6,
  color7: `light-dark(${ secondarySurfaceColors.light7 }, ${ secondarySurfaceColors.dark7 })`,
  alpha7: `light-dark(${ secondarySurfaceColors.lightA7 }, ${ secondarySurfaceColors.darkA7 })`,
  light7: secondarySurfaceColors.light7,
  lightA7: secondarySurfaceColors.lightA7,
  dark7: secondarySurfaceColors.dark7,
  darkA7: secondarySurfaceColors.darkA7,
  color8: `light-dark(${ secondarySurfaceColors.light8 }, ${ secondarySurfaceColors.dark8 })`,
  alpha8: `light-dark(${ secondarySurfaceColors.lightA8 }, ${ secondarySurfaceColors.darkA8 })`,
  light8: secondarySurfaceColors.light8,
  lightA8: secondarySurfaceColors.lightA8,
  dark8: secondarySurfaceColors.dark8,
  darkA8: secondarySurfaceColors.darkA8,
  color9: `light-dark(${ secondarySurfaceColors.light9 }, ${ secondarySurfaceColors.dark9 })`,
  alpha9: `light-dark(${ secondarySurfaceColors.lightA9 }, ${ secondarySurfaceColors.darkA9 })`,
  light9: secondarySurfaceColors.light9,
  lightA9: secondarySurfaceColors.lightA9,
  dark9: secondarySurfaceColors.dark9,
  darkA9: secondarySurfaceColors.darkA9,
  color10: `light-dark(${ secondarySurfaceColors.light10 }, ${ secondarySurfaceColors.dark10 })`,
  alpha10: `light-dark(${ secondarySurfaceColors.lightA10 }, ${ secondarySurfaceColors.darkA10 })`,
  light10: secondarySurfaceColors.light10,
  lightA10: secondarySurfaceColors.lightA10,
  dark10: secondarySurfaceColors.dark10,
  darkA10: secondarySurfaceColors.darkA10,
  color11: `light-dark(${ secondarySurfaceColors.light11 }, ${ secondarySurfaceColors.dark11 })`,
  alpha11: `light-dark(${ secondarySurfaceColors.lightA11 }, ${ secondarySurfaceColors.darkA11 })`,
  light11: secondarySurfaceColors.light11,
  lightA11: secondarySurfaceColors.lightA11,
  dark11: secondarySurfaceColors.dark11,
  darkA11: secondarySurfaceColors.darkA11,
  color12: `light-dark(${ secondarySurfaceColors.light12 }, ${ secondarySurfaceColors.dark12 })`,
  alpha12: `light-dark(${ secondarySurfaceColors.lightA12 }, ${ secondarySurfaceColors.darkA12 })`,
  light12: secondarySurfaceColors.light12,
  lightA12: secondarySurfaceColors.lightA12,
  dark12: secondarySurfaceColors.dark12,
  darkA12: secondarySurfaceColors.darkA12
});
