import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { tertiarySurfaceColors } from '../../colors/surface/tertiary.stylex';

export const surfaceTertiary = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ tertiarySurfaceColors.light1 }, ${ tertiarySurfaceColors.dark1 })`,
  alpha1: `light-dark(${ tertiarySurfaceColors.lightA1 }, ${ tertiarySurfaceColors.darkA1 })`,
  light1: tertiarySurfaceColors.light1,
  lightA1: tertiarySurfaceColors.lightA1,
  dark1: tertiarySurfaceColors.dark1,
  darkA1: tertiarySurfaceColors.darkA1,
  color2: `light-dark(${ tertiarySurfaceColors.light2 }, ${ tertiarySurfaceColors.dark2 })`,
  alpha2: `light-dark(${ tertiarySurfaceColors.lightA2 }, ${ tertiarySurfaceColors.darkA2 })`,
  light2: tertiarySurfaceColors.light2,
  lightA2: tertiarySurfaceColors.lightA2,
  dark2: tertiarySurfaceColors.dark2,
  darkA2: tertiarySurfaceColors.darkA2,
  color3: `light-dark(${ tertiarySurfaceColors.light3 }, ${ tertiarySurfaceColors.dark3 })`,
  alpha3: `light-dark(${ tertiarySurfaceColors.lightA3 }, ${ tertiarySurfaceColors.darkA3 })`,
  light3: tertiarySurfaceColors.light3,
  lightA3: tertiarySurfaceColors.lightA3,
  dark3: tertiarySurfaceColors.dark3,
  darkA3: tertiarySurfaceColors.darkA3,
  color4: `light-dark(${ tertiarySurfaceColors.light4 }, ${ tertiarySurfaceColors.dark4 })`,
  alpha4: `light-dark(${ tertiarySurfaceColors.lightA4 }, ${ tertiarySurfaceColors.darkA4 })`,
  light4: tertiarySurfaceColors.light4,
  lightA4: tertiarySurfaceColors.lightA4,
  dark4: tertiarySurfaceColors.dark4,
  darkA4: tertiarySurfaceColors.darkA4,
  color5: `light-dark(${ tertiarySurfaceColors.light5 }, ${ tertiarySurfaceColors.dark5 })`,
  alpha5: `light-dark(${ tertiarySurfaceColors.lightA5 }, ${ tertiarySurfaceColors.darkA5 })`,
  light5: tertiarySurfaceColors.light5,
  lightA5: tertiarySurfaceColors.lightA5,
  dark5: tertiarySurfaceColors.dark5,
  darkA5: tertiarySurfaceColors.darkA5,
  color6: `light-dark(${ tertiarySurfaceColors.light6 }, ${ tertiarySurfaceColors.dark6 })`,
  alpha6: `light-dark(${ tertiarySurfaceColors.lightA6 }, ${ tertiarySurfaceColors.darkA6 })`,
  light6: tertiarySurfaceColors.light6,
  lightA6: tertiarySurfaceColors.lightA6,
  dark6: tertiarySurfaceColors.dark6,
  darkA6: tertiarySurfaceColors.darkA6,
  color7: `light-dark(${ tertiarySurfaceColors.light7 }, ${ tertiarySurfaceColors.dark7 })`,
  alpha7: `light-dark(${ tertiarySurfaceColors.lightA7 }, ${ tertiarySurfaceColors.darkA7 })`,
  light7: tertiarySurfaceColors.light7,
  lightA7: tertiarySurfaceColors.lightA7,
  dark7: tertiarySurfaceColors.dark7,
  darkA7: tertiarySurfaceColors.darkA7,
  color8: `light-dark(${ tertiarySurfaceColors.light8 }, ${ tertiarySurfaceColors.dark8 })`,
  alpha8: `light-dark(${ tertiarySurfaceColors.lightA8 }, ${ tertiarySurfaceColors.darkA8 })`,
  light8: tertiarySurfaceColors.light8,
  lightA8: tertiarySurfaceColors.lightA8,
  dark8: tertiarySurfaceColors.dark8,
  darkA8: tertiarySurfaceColors.darkA8,
  color9: `light-dark(${ tertiarySurfaceColors.light9 }, ${ tertiarySurfaceColors.dark9 })`,
  alpha9: `light-dark(${ tertiarySurfaceColors.lightA9 }, ${ tertiarySurfaceColors.darkA9 })`,
  light9: tertiarySurfaceColors.light9,
  lightA9: tertiarySurfaceColors.lightA9,
  dark9: tertiarySurfaceColors.dark9,
  darkA9: tertiarySurfaceColors.darkA9,
  color10: `light-dark(${ tertiarySurfaceColors.light10 }, ${ tertiarySurfaceColors.dark10 })`,
  alpha10: `light-dark(${ tertiarySurfaceColors.lightA10 }, ${ tertiarySurfaceColors.darkA10 })`,
  light10: tertiarySurfaceColors.light10,
  lightA10: tertiarySurfaceColors.lightA10,
  dark10: tertiarySurfaceColors.dark10,
  darkA10: tertiarySurfaceColors.darkA10,
  color11: `light-dark(${ tertiarySurfaceColors.light11 }, ${ tertiarySurfaceColors.dark11 })`,
  alpha11: `light-dark(${ tertiarySurfaceColors.lightA11 }, ${ tertiarySurfaceColors.darkA11 })`,
  light11: tertiarySurfaceColors.light11,
  lightA11: tertiarySurfaceColors.lightA11,
  dark11: tertiarySurfaceColors.dark11,
  darkA11: tertiarySurfaceColors.darkA11,
  color12: `light-dark(${ tertiarySurfaceColors.light12 }, ${ tertiarySurfaceColors.dark12 })`,
  alpha12: `light-dark(${ tertiarySurfaceColors.lightA12 }, ${ tertiarySurfaceColors.darkA12 })`,
  light12: tertiarySurfaceColors.light12,
  lightA12: tertiarySurfaceColors.lightA12,
  dark12: tertiarySurfaceColors.dark12,
  darkA12: tertiarySurfaceColors.darkA12
});
