import * as stylex from '@stylexjs/stylex';
import { radixSurface } from '../../radix.stylex';
import { warningSurfaceColors } from '../../colors/surface/warning.stylex';

export const surfaceWarning = stylex.createTheme(radixSurface, {
  color1: `light-dark(${ warningSurfaceColors.light1 }, ${ warningSurfaceColors.dark1 })`,
  alpha1: `light-dark(${ warningSurfaceColors.lightA1 }, ${ warningSurfaceColors.darkA1 })`,
  light1: warningSurfaceColors.light1,
  lightA1: warningSurfaceColors.lightA1,
  dark1: warningSurfaceColors.dark1,
  darkA1: warningSurfaceColors.darkA1,
  color2: `light-dark(${ warningSurfaceColors.light2 }, ${ warningSurfaceColors.dark2 })`,
  alpha2: `light-dark(${ warningSurfaceColors.lightA2 }, ${ warningSurfaceColors.darkA2 })`,
  light2: warningSurfaceColors.light2,
  lightA2: warningSurfaceColors.lightA2,
  dark2: warningSurfaceColors.dark2,
  darkA2: warningSurfaceColors.darkA2,
  color3: `light-dark(${ warningSurfaceColors.light3 }, ${ warningSurfaceColors.dark3 })`,
  alpha3: `light-dark(${ warningSurfaceColors.lightA3 }, ${ warningSurfaceColors.darkA3 })`,
  light3: warningSurfaceColors.light3,
  lightA3: warningSurfaceColors.lightA3,
  dark3: warningSurfaceColors.dark3,
  darkA3: warningSurfaceColors.darkA3,
  color4: `light-dark(${ warningSurfaceColors.light4 }, ${ warningSurfaceColors.dark4 })`,
  alpha4: `light-dark(${ warningSurfaceColors.lightA4 }, ${ warningSurfaceColors.darkA4 })`,
  light4: warningSurfaceColors.light4,
  lightA4: warningSurfaceColors.lightA4,
  dark4: warningSurfaceColors.dark4,
  darkA4: warningSurfaceColors.darkA4,
  color5: `light-dark(${ warningSurfaceColors.light5 }, ${ warningSurfaceColors.dark5 })`,
  alpha5: `light-dark(${ warningSurfaceColors.lightA5 }, ${ warningSurfaceColors.darkA5 })`,
  light5: warningSurfaceColors.light5,
  lightA5: warningSurfaceColors.lightA5,
  dark5: warningSurfaceColors.dark5,
  darkA5: warningSurfaceColors.darkA5,
  color6: `light-dark(${ warningSurfaceColors.light6 }, ${ warningSurfaceColors.dark6 })`,
  alpha6: `light-dark(${ warningSurfaceColors.lightA6 }, ${ warningSurfaceColors.darkA6 })`,
  light6: warningSurfaceColors.light6,
  lightA6: warningSurfaceColors.lightA6,
  dark6: warningSurfaceColors.dark6,
  darkA6: warningSurfaceColors.darkA6,
  color7: `light-dark(${ warningSurfaceColors.light7 }, ${ warningSurfaceColors.dark7 })`,
  alpha7: `light-dark(${ warningSurfaceColors.lightA7 }, ${ warningSurfaceColors.darkA7 })`,
  light7: warningSurfaceColors.light7,
  lightA7: warningSurfaceColors.lightA7,
  dark7: warningSurfaceColors.dark7,
  darkA7: warningSurfaceColors.darkA7,
  color8: `light-dark(${ warningSurfaceColors.light8 }, ${ warningSurfaceColors.dark8 })`,
  alpha8: `light-dark(${ warningSurfaceColors.lightA8 }, ${ warningSurfaceColors.darkA8 })`,
  light8: warningSurfaceColors.light8,
  lightA8: warningSurfaceColors.lightA8,
  dark8: warningSurfaceColors.dark8,
  darkA8: warningSurfaceColors.darkA8,
  color9: `light-dark(${ warningSurfaceColors.light9 }, ${ warningSurfaceColors.dark9 })`,
  alpha9: `light-dark(${ warningSurfaceColors.lightA9 }, ${ warningSurfaceColors.darkA9 })`,
  light9: warningSurfaceColors.light9,
  lightA9: warningSurfaceColors.lightA9,
  dark9: warningSurfaceColors.dark9,
  darkA9: warningSurfaceColors.darkA9,
  color10: `light-dark(${ warningSurfaceColors.light10 }, ${ warningSurfaceColors.dark10 })`,
  alpha10: `light-dark(${ warningSurfaceColors.lightA10 }, ${ warningSurfaceColors.darkA10 })`,
  light10: warningSurfaceColors.light10,
  lightA10: warningSurfaceColors.lightA10,
  dark10: warningSurfaceColors.dark10,
  darkA10: warningSurfaceColors.darkA10,
  color11: `light-dark(${ warningSurfaceColors.light11 }, ${ warningSurfaceColors.dark11 })`,
  alpha11: `light-dark(${ warningSurfaceColors.lightA11 }, ${ warningSurfaceColors.darkA11 })`,
  light11: warningSurfaceColors.light11,
  lightA11: warningSurfaceColors.lightA11,
  dark11: warningSurfaceColors.dark11,
  darkA11: warningSurfaceColors.darkA11,
  color12: `light-dark(${ warningSurfaceColors.light12 }, ${ warningSurfaceColors.dark12 })`,
  alpha12: `light-dark(${ warningSurfaceColors.lightA12 }, ${ warningSurfaceColors.darkA12 })`,
  light12: warningSurfaceColors.light12,
  lightA12: warningSurfaceColors.lightA12,
  dark12: warningSurfaceColors.dark12,
  darkA12: warningSurfaceColors.darkA12
});
